spring.application.name=barbearia-api

# Configuracoes do MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/barbearia_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=989221517

# Hibernate
spring.jpa.hibernate.ddl-auto=update
